### ISSUE TITLE
Maximizing Popup only works correctly in single screen setup

### ISSUE THREAD

**Issue by Nomoresleep** [ands/borderless-window-opengl#2]
Because each monitor can have its own working area (depending for example on the location of the taskbar) maximizing a window is currently only working correctly on a single monitor or (in a dual monitor setup) on the main screen.

**Comment by ands** [comment]
Is that fixed for you with https://github.com/ands/borderless-window-opengl/commit/9da6560f3f3e8ab37a23ae77f6cd321caa29d6ba ?

**Comment by Nomoresleep** [comment]
Sadly no :(. It appears to be working the same as before. But I used it to create a working fix: https://github.com/Nomoresleep/borderless-window-opengl/commit/d485120935e6e0aa587b966b393ac7db53063800

**Comment by ands** [comment]
Closing this since your pull request was accepted :)
